export const HOTKEYS = {
  "mod+b": "bold",
  "mod+i": "italic",
  "mod+u": "underline",
  "mod+`": "code",
  "mod+s": "subject",
  "mod+a": "selectAll",
  "mod+shift+s": "strikethrough",
  "mod+enter": "enter",
  "mod+g": "suffix",
  tab: "autoComplete",
  "alt+t": "translate",
  "alt+enter": "code-suffix",
  "alt+h": "highlight",
};
