const productPath = [
  { url: "/app/tagline", label: "Tagline" },
  { url: "/app/landing-page-headline-description", label: "Landing Page Headline Description" },
  { url: "/app/landing-page-headline", label: "Landing Page Headline" },
  { url: "/app/meta-descriptions", label: "Meta Descriptions" },
  { url: "/app/question-generator", label: "Question Generator" },
  { url: "/app/sub-headers", label: "Sub Headers" },
  { url: "/app/keyword-finder", label: "Keyword Finder" },
  { url: "/app/subject-finder", label: "Subject Finder" },
  { url: "/app/blog-post-intro", label: "Blog Post Intro" },
  { url: "/app/blog-post-ideas", label: "Blog Post Ideas" },
  { url: "/app/blog-post-conclusion", label: "Blog Post Conclusion" },
  { url: "/app/blog-post-headline", label: "Blog Post Headline" },
  { url: "/app/blog-post-summary", label: "Blog Post Summary" },
  { url: "/app/blog-post-aida", label: "Blog Post Aida" },
  { url: "/app/blog-post-pas", label: "Blog Post Pas" },
  { url: "/app/paraphrase", label: "Paraphrase" },
  { url: "/app/grammar", label: "Grammar" },
  { url: "/app/mission-statement", label: "Mission Statement" },
  { url: "/app/vision-statement", label: "Vision Statement" },
  { url: "/app/value-proposition", label: "Value Proposition" },
  { url: "/app/adjust-tone-rewriting", label: "Adjust Tone" },
  { url: "/app/friendly-email", label: "Write business friendly email" },
  { url: "/app/followup-email", label: "Followup Email" },
  { url: "/app/cold-email", label: "Cold Email" },
  { url: "/app/thanks-you-email", label: "Thanks You Email" },
  { url: "/app/prospecting-email", label: "Prospecting Email" },
  { url: "/app/productdescription", label: "Product Description" },
  { url: "/app/productdescriptionamazon", label: "Product Description Amazon" },
];

export default productPath;
