

const productPath = [
  { url: "/app/tagline", label: "Tagline" },
  { url: "/app/landing-page-headline-description", label: "Landing Page Headline Description" },
  { url: "/app/landing-page-headline", label: "Landing Page Headline" },
  { url: "/app/meta-descriptions", label: "Meta Descriptions" },
  { url: "/app/question-generator", label: "Question Generator" },
  { url: "/app/sub-headers", label: "Sub Headers" },
  { url: "/app/keyword-finder", label: "Keyword Finder" },
  { url: "/app/subject-finder", label: "Subject Finder" },
  { url: "/app/blog-post-intro", label: "Blog Post Intro" },
  { url: "/app/blog-post-ideas", label: "Blog Post Ideas" },
  { url: "/app/blog-post-conclusion", label: "Blog Post Conclusion" },
  { url: "/app/blog-post-headline", label: "Blog Post Headline" },
  { url: "/app/blog-post-summary", label: "Blog Post Summary" },
  { url: "/app/blog-post-aida", label: "Blog Post Aida" },
  { url: "/app/blog-post-pas", label: "Blog Post Pas" },
  { url: "/app/paraphrase", label: "Paraphrase" },
  { url: "/app/grammar", label: "Grammar" },
  { url: "/app/mission-statement", label: "Mission Statement" },
  { url: "/app/vision-statement", label: "Vision Statement" },
  { url: "/app/value-proposition", label: "Value Proposition" },
  { url: "/app/adjust-tone-rewriting", label: "Rewrite - Adjust Tone" },
  { url: "/app/friendly-email", label: "Write business friendly email" },
  { url: "/app/followup-email", label: "Followup Email" },
  { url: "/app/cold-email", label: "Cold Email" },
  { url: "/app/thanks-you-email", label: "Thanks You Email" },
  { url: "/app/prospecting-email", label: "Prospecting Email" },
  { url: "/app/productdescription", label: "Product Description" },
  { url: "/app/productdescriptionamazon", label: "Product Description Amazon" },
  { url: "/app/g-ad-title", label: "Google Ad Tilte" },
  { url: "/app/g-ad-description", label: "Google Ad Description" },
  { url: "/app/create-outline", label: "Create Outline" },
  { url: "/app/expand", label: "Expand an outline" },
];

export default productPath;



interface productsTools {
  label: string;
  path: string;
  message: string;
  mainPlaceholder: string;
  productType: string;
  generateButtonName: string;
  toneTextField: boolean;
  headerTitle: string;
  labelsLists: any[];
  inputLimitation: string;
}[]



export const toolLists = [
  {
    label: "Blog Post Intro",
    headerTitle: "Blog Post Intro",
    path: "/blog-post-intro",
    description: "It is used to introduce the topic of the blog post and to provide a brief overview of what the reader can expect to learn by reading the blog post.",
    instructHelp: "what you want your readers to take away or any background to the blog you're writing, we'll create a blog post intro based on that.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly. -> Introducing the newest addition to the coffee lover's arsenal - the reusable cup! This cup is made of Eco-friendly materials and keeps coffee warm, so you can enjoy your drink on the go.",
    productType: "24",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Blog Post Conclusion",
    headerTitle: "Blog Post Conclusion",
    path: "/blog-post-conclusion",
    description: "A blog post conclusion wraps up the main points of the blog post and provides a brief summary of what the reader has learned.",
    instructHelp: "Write a few paragraphs of your blog and then we'll create a conclusion of the blog post based on that.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "50",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "200",
  },
  {
    label: "Blog Post Aida",
    headerTitle: "Blog Post Attention- Interest- Desire- Action",
    path: "/blog-post-aida",
    description: "It can be used to help you create a persuasive and attention-grabbing blog post by outlining the key points that you want to cover in your post.",
    instructHelp: "Write about your product or an idea; then we will use AIDA: Attention, Interest, Desire, Action for it.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "150",
  },
  
  {
    label: "Blog Post Idea",
    headerTitle: "Blog Post Ideas",
    path: "/blog-post-ideas",
    description: "blog post ideas can be used as a way to brainstorm new blog posts which is helpful to find a new ideas for your contents.",
    instructHelp: "Write about your product or an idea; then we will provide you blog post ideas.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "30",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "150",
  },
  {
    label: "Blog Post Headline",
    headerTitle: "Blog Post Headline",
    path: "/blog-post-headline",
    description: "A blog post headline can help you to come up with a catchy headline for your blog post.",
    instructHelp: "Write a few paragraphs of your blog here, and we'll give you a title for your blog post.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "60",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Blog Post Summary",
    headerTitle: "Blog Post Summary",
    path: "/blog-post-summary",
    description: "It can be used to summarize the blog post and provide a concise description.",
    instructHelp: "Write a few paragraphs about your blog here or any other idea; then we'll create a summary blog post for it.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "30",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "150",
  },
  {
    label: "Paraphrase",
    headerTitle: "Paraphrase",
    path: "/paraphrase",
    description: "It can be used to rewrite a text to improve its readability and to ensure that the meaning of the text is retained.",
    instructHelp: "Write about your product or an idea; then we will paraphrase it for you.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "45",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Mission Statement",
    headerTitle: "Mission Statement",
    path: "/mission-statement",
    description: "A mission statement is a declaration of the purpose of a company or organization. It is a statement of the organization's core values and beliefs, and its overall goal or purpose.",
    instructHelp: "Write a few paragraphs about your business or product; then we'll create a mission statement for it.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Vision Statement",
    headerTitle: "Vision Statement",
    path: "/vision-statement",
    description: "A vision statement is a declaration of the company's purpose or a declaration of what the company hopes to achieve in the future.",
    instructHelp:
      "Write a few paragraphs about your business or product; then we'll create a vision statement for it.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Value Proposition",
    headerTitle: "Value Proposition",
    path: "/value-proposition",
    description: "A value proposition is a statement that summarizes the benefit that a customer will receive by using a particular product or service.",
    instructHelp: "Write a few paragraphs about your business or product; then we'll create a value proposition for it.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Rewrite - Adjust Tone",
    headerTitle: "Rewrite - Adjust Tone",
    path: "/rewrite-adjust-tone",
    description: "It can be used to adjust the tone of a document to make it more persuasive or to match the tone of the company's branding.",
    instructHelp: "Write a few paragraphs about your company or product, then we'll write about it in a different tone and voice.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Write business friendly email",
    headerTitle: "Write business friendly email",
    path: "/write-business-friendly-email",
    description: "It can be used to draft a professional and friendly email to a colleague or client.",
    instructHelp: "Write the main point you want to address in this email, and then we'll create a friendly email based on it.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Follow-up Email",
    headerTitle: "Followup Email",
    path: "/followup-email",
    description: "A followup email can be used to remind a customer about a product they were interested in or to provide additional information about a product they have already purchased.",
    instructHelp: "Write the main point you want to raise in this email, and then we'll wrap it up with a follow-up template in the best possible way.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Cold Email",
    headerTitle: "Cold Email",
    path: "/cold-email",
    description: "A cold email is a message that is sent to a potential customer who has not been previously contacted by the sender. It is used to introduce a product or service and to request a meeting or an opportunity to discuss the product or service further.",
    instructHelp: "Write a few paragraphs about your business or product; then we'll wrap it up with a cold template in the best possible way.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Thanks You Email",
    headerTitle: "Thanks You Email",
    path: "/thanks-you-email",
    description: "Acknowledging and thanking someone for their help or support can be a great way to show your appreciation and to strengthen the relationship.",
    instructHelp: "Write a few paragraphs about your business or product; then we'll wrap it up with a thanks you template in the best possible way.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Prospecting Email",
    headerTitle: "Prospecting Email",
    path: "/prospecting-email",
    description: "Prospecting email is a type of email that is sent to potential customers in order to generate leads and interest in a product or service.",
    instructHelp: "Write a few paragraphs about your business or product; then we'll wrap it up with a prospecting template in the best possible way.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Grammar",
    headerTitle: "Grammar",
    path: "/grammar",
    description: "AI-powered grammar tools can help to improve the grammar and punctuation of your writing.",
    instructHelp: "Write a few paragraphs; then we improve the grammar of the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "checking spell and grammar",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Subject Suggestion",
    headerTitle:
      "Subject Suggestion",
    path: "/subject-suggestion",
    description: "It can be used to identify the subject of a document to improve the SEO of a page.",
    instructHelp: "Write a few paragraphs; then we'll suggest a subject for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Meta Descriptions",
    headerTitle: "Meta Descriptions",
    path: "/meta-descriptions",
    description: "It can be used to create meta descriptions, which are short summaries of the page that appear in search engine results.",
    instructHelp: "Write a few paragraphs; then we'll create a meta description for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Product Description",
    headerTitle: "Product Description",
    path: "/productdescription",
    description: "It can be used to create a well-written and informative product description for Amazon.",
    instructHelp: "Write a few paragraphs; then we'll create a Product Description for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Product Description Amazon",
    headerTitle: "Product Description Amazon",
    path: "/productdescriptionamazon",
    description: "It can be used to create a content to improve SEO of a page.",
    instructHelp: "Write a few paragraphs; then we'll create a Product Description for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "create outline",
    headerTitle: "create outline",
    path: "/create-outline",
    description: "It can be used to help you create an outline for your blog post, which can make the writing process easier and help you to stay on track.",
    instructHelp: "Write a few paragraphs; then we'll create an outline for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "expand outline",
    headerTitle: "expand outline",
    path: "/expand",
    description: "It can be used to expand the ideas presented in an outline to help you write a more detailed and comprehensive document.",
    instructHelp: "Write a few paragraphs; then we'll expand the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "keyword-finder",
    headerTitle: "keyword Suggestion",
    path: "/keyword-finder",
    description: "It helps you find the best target keywords for your content and how optimized your content can be for search engines with different keywords.",
    instructHelp: "Write a few paragraphs; then we'll find the best keywords for the given text that is optimized for search engines and your content that conveys that.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "paraphrase",
    headerTitle: "paraphrase",
    path: "/paraphrase",
    description: "It can be used to rewrite a text to improve its readability and to ensure that the meaning of the text is retained.",
    instructHelp: "Write a few paragraphs; then we'll paraphrase the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Question Generator",
    headerTitle: "Question Generator",
    path: "/question-generator",
    description: "It can be used to generate a question from a paragraph or for a particular topic.",
    instructHelp: "Write a few paragraphs; then we'll generate a question for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Sub Headers",
    headerTitle: "Sub Headers",
    path: "/sub-headers",
    description: "It is useful to create an additional heading or title immediately after the main heading or title of a text block.",
    instructHelp: "Write a few paragraphs; then we'll create a sub header for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Landing Page Headline Description",
    headerTitle: "Landing Page Headline Description",
    path: "/landing-page-headline-description",
    description: "It can be used to create a short and catchy description that invites users to learn more about the product or service.",
    instructHelp: "Write a few paragraphs; then we'll create a Landing Page Headline Description for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Landing Page Headline",
    headerTitle: "Landing Page Headline",
    path: "/landing-page-headline",
    description: "Landing page headlines can help you to come up with a catchy headline for your landing page.",
    instructHelp: "Write a few paragraphs; then we'll create a Landing Page Headline for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Blog Post Aida",
    headerTitle: "Blog Post Aida",
    path: "/blog-post-aida",
    description: "AIDA: Attention - Interest - Desire - Action is the most well-known copywriting technique that makes copywriting very easy, simple and successful. The AIDA model is a framework used in marketing and advertising to describe the process that occurs from the very first moment when a consumer becomes aware of a product or brand to the actual moment of purchase.",
    instructHelp: "Write a few paragraphs; then we'll create a Aida for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
  {
    label: "Blog Post Pas",
    headerTitle: "Blog Post Pas",
    path: "/blog-post-pas",
    description: "Pain, Agitate, Solve. Or Problem, Agitate, Solution. If you want to write a good copy, you should think about the problem that your reader is experiencing, and then agitate that problem. Finally, offer a solution that will make the reader's life better.",
    instructHelp: "Write a few paragraphs and then we will create a problem, an agitation and a solution for the given text.",
    example: "a reusable cup that keeps coffee warm and is Eco-friendly.",
    productType: "25",
    generateButtonName: "Compose",
    toneTextField: true,
    labelsLists: [],
    inputLimitation: "250",
  },
]
