/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.GATSBY_APP_AWS_PROJECT_REGION,
    "aws_cognito_identity_pool_id": process.env.GATSBY_APP_AWS_COGNITO_IDENTITY_POOL_ID,
    "aws_cognito_region": process.env.GATSBY_APP_AWS_COGNITO_REGION,
    "aws_user_pools_id": process.env.GATSBY_APP_AWS_USER_POOLS_ID,
    "aws_user_pools_web_client_id": process.env.GATSBY_APP_AWS_USER_POOLS_WEB_CLIENT_ID,
    "oauth": {
        "domain": process.env.GATSBY_APP_OAUTH_DOMAIN,
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": process.env.GATSBY_APP_OAUTH_REDIRECT_SIGN_IN,
        "redirectSignOut": process.env.GATSBY_APP_OAUTH_REDIRECT_SIGN_OUT,
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": process.env.GATSBY_APP_AWS_CONTENT_DELIVERY_BUCKET,
    "aws_content_delivery_bucket_region": process.env.GATSBY_APP_AWS_CONTENT_DELIVERY_BUCKET_REGION,
    "aws_content_delivery_url": process.env.GATSBY_APP_AWS_CONTENT_DELIVERY_URL
};


export default awsmobile;

